<?php
/**
 * Template for displaying Downloads Archive in EDD
 *
 * Note for customisers/users: Do not edit this file!
 * ===================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in your child theme's root folder or "edd" subfolder, i.e. /wp-content/themes/your-child-theme/edd/
 * (Your theme may not have a "edd" folder, so just create one.)
 * The version in the child theme's root/"edd" folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 * @since 1.0.0
 */

add_action( 'genesis_before_loop', 'gcedd_archive_top_widget' );
/**
 * Add the optional top widget for the download archive
 *
 * @since 1.0.0
 *
 * @uses  is_search()
 * @uses  genesis_widget_area()
 */
function gcedd_archive_top_widget() {

	/** Only display if not on a search page */
	if ( ! is_search() ) {

		genesis_widget_area(
			'gcedd-archive-top',
			array(
				//'before' => '<div class="gcedd-archive widget-area">',
				//'after'  => '</div>',
				'before' => current_theme_supports( 'html5' ) ? '<aside class="gcedd-archive widget-area">' : '<div class="gcedd-archive widget-area">',
				'after'  => current_theme_supports( 'html5' ) ? '</aside>' : '</div>',
			)
		);

	}  // end-if is_search check

}  // end of function gcedd_archive_top_widget

/**
 * Archive Post Class
 * @since 1.0.0
 *
 * Breaks the posts into two or three columns
 * @link http://www.billerickson.net/code/grid-loop-using-post-class
 *
 * @param array $classes
 * @return array
 */
function custom_archive_post_class( $classes ) {

	$classes[] = 'one-third';
	global $wp_query;
	if( 0 == $wp_query->current_post || 0 == $wp_query->current_post % 3 )
		$classes[] = 'first';
	return $classes;
}

add_filter( 'post_class', 'custom_archive_post_class' );


//* Remove the entry meta in the entry header
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );

//* Remove the post content for the blog and archive pages
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );



/** Let Genesis take over :) */
genesis();
